version: '3.3'
services:
  web:
    build: .
    ports:
      - "9000:8080"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo/book
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: